name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  pnpm-version: 10.2.1
  node-version: 23

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:ci

      - name: Install browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint
