name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  PNPM_VERSION: 10.2.1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Install browsers
        run: cd packages/agent && pnpm exec playwright install --with-deps chromium

      - name: Test
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: pnpm test

      - name: Lint
        run: pnpm lint
