name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.2.1

      - uses: actions/setup-node@v3
        with:
          node-version: 23

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build
        run: pnpm build:ci

      - name: Install browsers
        run: pnpm exec playwright install

      - name: Test
        run: pnpm test
