name: MyCoder Issue Comment Action

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  PNPM_VERSION: 10.2.1

jobs:
  process-comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/mycoder pr') || contains(github.event.comment.body, '/mycoder plan')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: Install MyCoder
        run: pnpm install -g mycoder

      - name: Run MyCoder PR command
        if: contains(github.event.comment.body, '/mycoder pr')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          echo "Running MyCoder to implement PR for issue #${{ github.event.issue.number }}"
          mycoder --githubMode true "Implement a PR for GitHub issue #${{ github.event.issue.number }}. The issue can be found at ${{ github.event.issue.html_url }}. Please review the issue details and implement a solution according to the requirements. After implementation, create a pull request that addresses this issue."

      - name: Run MyCoder Plan command
        if: contains(github.event.comment.body, '/mycoder plan')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        run: |
          echo "Running MyCoder to create implementation plan for issue #${{ github.event.issue.number }}"
          mycoder --githubMode true "Review GitHub issue #${{ github.event.issue.number }} at ${{ github.event.issue.html_url }} and create an implementation plan. Post your plan as a comment on the issue. Be thorough and consider all requirements mentioned in the issue description."