name: MyCoder Issue Comment Action

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  PNPM_VERSION: 10.2.1

jobs:
  process-comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/mycoder')
    steps:
      - name: Extract prompt from comment
        id: extract-prompt
        run: |
          echo "comment_url=${{ github.event.comment.html_url }}" >> $GITHUB_OUTPUT
          echo "comment_id=${{ github.event.comment.id }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - run: pnpm install -g mycoder

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "Running MyCoder for issue #${{ github.event.issue.number }} with prompt: ${{ steps.extract-prompt.outputs.prompt }}"
          mycoder --userWarning false --upgradeCheck false --githubMode true --userPrompt false "On issue #${{ github.event.issue.number }} in comment ${{ steps.extract-prompt.outputs.comment_url }} the user invoked the mycoder CLI via /mycoder.  Can you try to do what they requested or if it is unclear, respond with a comment to that affect to encourage them to be more clear."
