name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

env:
  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.PNPM_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: cd packages/agent && pnpm exec playwright install --with-deps chromium
      - run: pnpm test
      - run: pnpm verify-release-config
      - run: |
          git config --global user.email "neuralsoft@gmail.com"
          git config --global user.name "Ben Houston (via GitHub Actions)"
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release
